biocypher:
    debug: true
    offline: true
    schema_config_path: schema.yaml

    # Ontology configuration
    head_ontology:
        url: https://raw.githubusercontent.com/biolink/biolink-model/refs/tags/v4.2.5/project/owl/biolink_model.owl.ttl
        root_node: entity

neo4j:
    database_name: neo4j
    wipe: true
    delimiter: ';'
    array_delimiter: '|'
    skip_duplicate_nodes: true
    skip_bad_relationships: true

    # MultiDB functionality
    # Set to false for using community edition or older versions of Neo4j
    multi_db: false

    import_call_bin_prefix: ''

